version: '3.3'

services:
  db:
    image: mm
#    volumes:
#      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
    restart: always
    container_name: mmc
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    ports:
      - '3333:3306'
    expose:
      - '3333'